/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersIndexImport } from './routes/users/index'
import { Route as TermsIndexImport } from './routes/terms/index'
import { Route as RulesIndexImport } from './routes/rules/index'
import { Route as RolesIndexImport } from './routes/roles/index'
import { Route as ProductsIndexImport } from './routes/products/index'
import { Route as ProductKitsIndexImport } from './routes/product-kits/index'
import { Route as LogicBlocksIndexImport } from './routes/logic-blocks/index'
import { Route as GroupsIndexImport } from './routes/groups/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const UsersIndexRoute = UsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any)

const TermsIndexRoute = TermsIndexImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRoute,
} as any)

const RulesIndexRoute = RulesIndexImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => rootRoute,
} as any)

const RolesIndexRoute = RolesIndexImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsIndexRoute = ProductsIndexImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRoute,
} as any)

const ProductKitsIndexRoute = ProductKitsIndexImport.update({
  id: '/product-kits/',
  path: '/product-kits/',
  getParentRoute: () => rootRoute,
} as any)

const LogicBlocksIndexRoute = LogicBlocksIndexImport.update({
  id: '/logic-blocks/',
  path: '/logic-blocks/',
  getParentRoute: () => rootRoute,
} as any)

const GroupsIndexRoute = GroupsIndexImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsIndexImport
      parentRoute: typeof rootRoute
    }
    '/logic-blocks/': {
      id: '/logic-blocks/'
      path: '/logic-blocks'
      fullPath: '/logic-blocks'
      preLoaderRoute: typeof LogicBlocksIndexImport
      parentRoute: typeof rootRoute
    }
    '/product-kits/': {
      id: '/product-kits/'
      path: '/product-kits'
      fullPath: '/product-kits'
      preLoaderRoute: typeof ProductKitsIndexImport
      parentRoute: typeof rootRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexImport
      parentRoute: typeof rootRoute
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesIndexImport
      parentRoute: typeof rootRoute
    }
    '/rules/': {
      id: '/rules/'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesIndexImport
      parentRoute: typeof rootRoute
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/groups': typeof GroupsIndexRoute
  '/logic-blocks': typeof LogicBlocksIndexRoute
  '/product-kits': typeof ProductKitsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/roles': typeof RolesIndexRoute
  '/rules': typeof RulesIndexRoute
  '/terms': typeof TermsIndexRoute
  '/users': typeof UsersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/groups': typeof GroupsIndexRoute
  '/logic-blocks': typeof LogicBlocksIndexRoute
  '/product-kits': typeof ProductKitsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/roles': typeof RolesIndexRoute
  '/rules': typeof RulesIndexRoute
  '/terms': typeof TermsIndexRoute
  '/users': typeof UsersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/groups/': typeof GroupsIndexRoute
  '/logic-blocks/': typeof LogicBlocksIndexRoute
  '/product-kits/': typeof ProductKitsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/rules/': typeof RulesIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/users/': typeof UsersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups'
    | '/logic-blocks'
    | '/product-kits'
    | '/products'
    | '/roles'
    | '/rules'
    | '/terms'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups'
    | '/logic-blocks'
    | '/product-kits'
    | '/products'
    | '/roles'
    | '/rules'
    | '/terms'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/groups/'
    | '/logic-blocks/'
    | '/product-kits/'
    | '/products/'
    | '/roles/'
    | '/rules/'
    | '/terms/'
    | '/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  LogicBlocksIndexRoute: typeof LogicBlocksIndexRoute
  ProductKitsIndexRoute: typeof ProductKitsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  RulesIndexRoute: typeof RulesIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  LogicBlocksIndexRoute: LogicBlocksIndexRoute,
  ProductKitsIndexRoute: ProductKitsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  RulesIndexRoute: RulesIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/groups/",
        "/logic-blocks/",
        "/product-kits/",
        "/products/",
        "/roles/",
        "/rules/",
        "/terms/",
        "/users/"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/groups/": {
      "filePath": "groups/index.jsx"
    },
    "/logic-blocks/": {
      "filePath": "logic-blocks/index.jsx"
    },
    "/product-kits/": {
      "filePath": "product-kits/index.jsx"
    },
    "/products/": {
      "filePath": "products/index.jsx"
    },
    "/roles/": {
      "filePath": "roles/index.jsx"
    },
    "/rules/": {
      "filePath": "rules/index.jsx"
    },
    "/terms/": {
      "filePath": "terms/index.jsx"
    },
    "/users/": {
      "filePath": "users/index.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
